### ISSUE TITLE
Create Docker Container only WebApp Folder

### ISSUE THREAD

**Issue by aryasoni98** [aryasoni98/AI-Interview#12]

**Comment by harikishantk** [comment]
I would like to work on it.

**Comment by aryasoni98** [comment]
@harikishantk Go head

**Comment by aryasoni98** [comment]
@harikishantk any update !!!

**Comment by harikishantk** [comment]
I had finished creating `dockerfile` and `docker-compose.yml` files. I'm trying to test by running the container but there is problem with `requirements.txt` already.

**Comment by aryasoni98** [comment]
> I had finished creating `dockerfile` and `docker-compose.yml` files. I'm trying to test by running the container but there is a problem with `requirements.txt` already.

Do one thing 1st install all dependencies and run the `app.py` then use this command `pip3 freeze > requirements.txt`.

**Comment by aryasoni98** [comment]
@harikishantk update me asap !!

**Comment by harikishantk** [comment]
> @harikishantk update me asap !!

https://github.com/aryasoni98/AI-Interview/pull/39#issuecomment-997418796
