### ISSUE TITLE
Fix Navbar CSS and header section on landing page

### ISSUE THREAD

**Issue by sonali-singh97** [aryasoni98/AI-Interview#21]
- Remove redundant lines from the header section
- Add consistent space between nav links.

![image](https://user-images.githubusercontent.com/56023695/144649568-1cf6777b-6432-41e7-bd66-c1ec01e3aab5.png)

**Comment by Aniket-508** [comment]
@sonali-singh97 Can I work on this?

**Comment by sonali-singh97** [comment]
Sure, You can start working on it.

**Comment by Aniket-508** [comment]
@aryasoni98 Which folder exactly do I have to work on? Like I can see there are two folders WebApp and Application.

**Comment by Aniket-508** [comment]
![Screenshot (147)](https://user-images.githubusercontent.com/71957423/145707195-cc858f17-ad54-4637-b2a4-3980c9695ffa.png)

**Comment by sonali-singh97** [comment]
In the previous code, the "Test & Develop" line was repeated twice. I was referring to that.

**Comment by Aniket-508** [comment]
So should I create a PR for this? @sonali-singh97

**Comment by aryasoni98** [comment]
> So should I create a PR for this? @sonali-singh97
Yes sure
