### ISSUE TITLE
Fix the height and spacing on Video and Audio page

### ISSUE THREAD

**Issue by sonali-singh97** [aryasoni98/AI-Interview#23]
- Decrease the space between the "audio interview" heading and Navbar on the Audio/Video page.
- Decrease the height of the section to fit into the whole screen.

**Comment by Aniket-508** [comment]
@sonali-singh97 Can I work on this?

**Comment by sonali-singh97** [comment]
Sure, you can.

**Comment by aryasoni98** [comment]
> @sonali-singh97 Can I work on this?
@Aniket-508 Go head .

**Comment by Aniket-508** [comment]
![Screenshot (151)](https://user-images.githubusercontent.com/71957423/145757162-b673b59c-1a93-4d11-bb47-04d6c35ad4c4.png)

Does this look good? @aryasoni98 @sonali-singh97

**Comment by sonali-singh97** [comment]
It's looking good. Just one more thing, try to remove the scroll from the page by decreasing the image height.
