### ISSUE TITLE
Connect Flask video frame to React web

### ISSUE THREAD

**Issue by sonali-singh97** [aryasoni98/AI-Interview#30]
Connect the Flask video API ('/video_1') to the frontend video interview page.

**Comment by prabhashkumar11** [comment]
Can I work on this sir?

**Comment by aryasoni98** [comment]
@prabhashkumar11 Yes sure !!

**Comment by aryasoni98** [comment]
@prabhashkumar11 any update!

**Comment by prabhashkumar11** [comment]
doing sir

**Comment by aryasoni98** [comment]
> doing sir
Update me asap!

**Comment by prabhashkumar11** [comment]
Practicals and submission are going in my college, so it is not possible for me till 31st to do any work.
