### ISSUE TITLE
Remove typos from README.md

### ISSUE THREAD

**Issue by harshitasao** [aryasoni98/AI-Interview#74]
## 📚 Documentation

(A clear and concise description of what the issue is.)

 To make  [README.md](https://github.com/aryasoni98/AI-Interview/blob/master/README.md)  easier to understand and remove confusion, fix the typo on line 86.

From this :

 `CMd pipwin install pyaudio`

To this:

 `CMD pipwin install pyaudio`

**Comment by aryasoni98** [comment]
@harshitasao Welcome to AI Interview🥳 Thanks for opening this Issue 🙌, This Will definitely Improve our Project💖.While we are having a look at this. If you want to work on this then,feel free to self-assign and start working on it.📄  **Use `/assign` to self-assign this issue**.
