### ISSUE TITLE
Typo in README.md

### ISSUE THREAD

**Issue by Rushijaviya** [aryasoni98/AI-Interview#75]
## 📚 Documentation

One typo in the sentence "We developed a AI interview emotion recognition platform to analysis the emotions of job candidates." here it should be "We developed an AI interview emotion recognition platform to analysis the emotions of job candidates."

**Comment by aryasoni98** [comment]
@Rushijaviya Welcome to AI Interview🥳 Thanks for opening this Issue 🙌, This Will definitely Improve our Project💖.While we are having a look at this. If you want to work on this then,feel free to self-assign and start working on it.📄  **Use `/assign` to self-assign this issue**.

**Comment by Rushijaviya** [comment]
I am a GSSOC'22 contributor.  Can you add the GSSOC label?

**Comment by Rushijaviya** [comment]
`/assign`

**Comment by Rushijaviya** [comment]
@aryasoni98 Hi! I'm a GSSOC 2022 contributor. can you add the GSSOC label?
